services:
  
  model-server:
    container_name: model-server
    build: 
      context: .
      dockerfile: docker/Dockerfile.server

    ports:
      - 5000:5000

  dashboard:
    container_name: dashboard
    build: 
      context: .
      dockerfile: docker/Dockerfile.dashboard

    ports:
      - 8501:8501

    env_file:
      - .env

    depends_on:
      model-server: 
        condition: service_started